### ISSUE TITLE
require-dev setting should be used on composer.json file

### ISSUE THREAD

**Issue by peter279k** [vaclavvanik/dom-loader#1]
As title, it seems that the `require-dev` is defined, but not used on `composer.json` file.

After checking the [tools](https://github.com/vaclavvanik/dom-loader/tree/master/tools) folder, it seems that `PHP_CodeSniffer` and `PHPUnit` version definitions should be moved to `require-dev` setting and their setting files can also be moved to the repository root folder.

**Comment by vaclavvanik** [comment]
`PHP_CodeSniffer` and `PHPUnit` have their own composer.json files. This allows custom dependencies and settings for every `tool`.

**Comment by peter279k** [comment]
The `require-dev` setting is for dependencies when setting up development environment.

I think `PHP_CodeSniffer` and `PHPUnit` should be development dependencies. And they're not belong to `require` setting.

**Comment by vaclavvanik** [comment]
Do you have any issues caused by current `tools` composer setup?
